services:
  doc:
    image: workflows-doc:latest
    build:
      context: .
    ports:
      - "6400:8000"
    logging:
      driver: "none"
    environment:
      PUID: 1030
      PGID: 65538
      TZ: Australia/Melbourne
